### ISSUE TITLE
Vložení se nepodařilo. Chyba: max number of attempts has been reached

### ISSUE THREAD

**Issue by Lenyska** [moravianlibrary/MEditor#16]
- vytvořit ze souborů na disku
- připojit k digitálnímu objektu
- PID
- pak se viditelně nic neděje
- po kliku na Vytvořit (dvě zelené šipky) dostaneme tuto hlášku:
![medit](https://cloud.githubusercontent.com/assets/11989702/7225890/58aa0c76-e743-11e4-988f-48b92a58d6e2.jpg)

**Comment by black23** [comment]
ID pro Z39.50 je 000088411

**Comment by Lenyska** [comment]
Po upgrade původní chyba se již neprojevila, ale po vytvoření objektu vyskočila tato:
![chyba](https://cloud.githubusercontent.com/assets/11989702/7699175/40009c28-fe16-11e4-8bf1-2303a61a91a2.jpg)
Michal pošle log

**Comment by MartinRumanek** [comment]
@Lenyska Tuto chybu jsem právě opravil. Jenom prosím upozorňuji, nehýbejte si s tou imortní strukturou. Pokud se objekt uloží a potom ty obrázky v importním adresáři přesunete jinam, tak se to rozbije.

Například teď tam je cesta "periodical/ct_zpravodaj/2012/01_leden_2012PR/txt/0001.txt"

Ale adresář  01_leden_2012PR už neexistuje. Když se tato struktura použije při importu tak to spadne do podobné chyby.

**Comment by Lenyska** [comment]
Další pokus:  
Vložení se nepodařilo. Chyba: Unkown file path for af7d6dbb-69f7-34a1-8bcb-94226d826fbd

**Comment by MartinRumanek** [comment]
Logy

```
meditor_1         |  com.gwtplatform.dispatch.shared.ActionException: Unkown file path for af7d6dbb-69f7-34a1-8bcb-94226d826fbd
meditor_1         | 	at cz.mzk.editor.server.handler.InsertNewDigitalObjectHandler.execute(InsertNewDigitalObjectHandler.java:191)
meditor_1         | 	at cz.mzk.editor.server.handler.InsertNewDigitalObjectHandler.execute(InsertNewDigitalObjectHandler.java:67)
meditor_1         | 	at com.gwtplatform.dispatch.server.AbstractDispatchImpl.doExecute(AbstractDispatchImpl.java:156)
meditor_1         | 	at com.gwtplatform.dispatch.server.AbstractDispatchImpl.execute(AbstractDispatchImpl.java:112)
meditor_1         | 	at com.gwtplatform.dispatch.server.AbstractDispatchServiceImpl.execute(AbstractDispatchServiceImpl.java:84)
meditor_1         | 	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
meditor_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
meditor_1         | 	at java.lang.reflect.Method.invoke(Method.java:606)
meditor_1         | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
meditor_1         | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
meditor_1         | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
meditor_1         | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
meditor_1         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
meditor_1         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
meditor_1         | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
meditor_1         | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
meditor_1         | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
meditor_1         | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
meditor_1         | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
meditor_1         | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
meditor_1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
meditor_1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
meditor_1         | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
meditor_1         | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
meditor_1         | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
meditor_1         | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
meditor_1         | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
meditor_1         | 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:481)
meditor_1         | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
meditor_1         | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
meditor_1         | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
meditor_1         | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
meditor_1         | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
meditor_1         | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
meditor_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
meditor_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
meditor_1         | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
meditor_1         | 	at java.lang.Thread.run(Thread.java:745)
```
