### ISSUE TITLE
Nejde najít metadata protokolem Z39.50

### ISSUE THREAD

**Issue by jirikrepl** [moravianlibrary/MEditor#50]
Dojde k chybě při pokusu stáhnout metadata. 

V třídě [Z3950ClientImpl.java](https://github.com/moravianlibrary/MEditor/blob/master/editor-common/editor-common-server/src/main/java/cz/mzk/editor/server/metadataDownloader/Z3950ClientImpl.java) se pomocí [funkce search](https://github.com/moravianlibrary/MEditor/blob/master/editor-common/editor-common-server/src/main/java/cz/mzk/editor/server/metadataDownloader/Z3950ClientImpl.java#L123) hledají marc metadata.

Uvnitř [funce search](https://github.com/moravianlibrary/MEditor/blob/master/editor-common/editor-common-server/src/main/java/cz/mzk/editor/server/metadataDownloader/Z3950ClientImpl.java#L223) se volá knihovna [ki-jzkit-iface-1.2.3.jar](https://github.com/moravianlibrary/MEditor/blob/master/pom.xml#L354)

toto volání zkončí chybou:

```
Exception in thread "Z3950 Search Thread aleph.mzk.cz" java.lang.NoClassDefFoundError: org/marc4j/MarcHandler
        at com.k_int.z3950.IRClient.Z3950SearchTask.processRecords(Z3950SearchTask.java:264)
        at com.k_int.z3950.IRClient.PresentCallbackHandler.notifyPresentResponse(PresentCallbackHandler.java:55)
        at com.k_int.z3950.IRClient.Z3950Origin.incomingPresentResponse(Z3950Origin.java:978)
        at com.k_int.z3950.util.GenericEventToOriginListenerAdapter.update(GenericEventToOriginListenerAdapter.java:66)
        at java.util.Observable.notifyObservers(Observable.java:159)
        at com.k_int.z3950.util.ZEndpoint.notifyAPDUEvent(ZEndpoint.java:238)
        at com.k_int.z3950.util.ZEndpoint.run(ZEndpoint.java:774)
        Caused by: java.lang.ClassNotFoundException: org.marc4j.MarcHandler
        at java.lang.ClassLoader.findClass(ClassLoader.java:531)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:407)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
        ... 7 more
```

**Comment by black23** [comment]
nepomuze implementovat klienta YAZ, ktery je standardem?
http://www.indexdata.com/yaz4j

**Comment by jirikrepl** [comment]
ano budeme se tohle snažit implementovat
http://www.indexdata.com/yaz4j

je potřeba udělat build aby jsme získali .so (shared object) Linuxovou knihovnu
https://github.com/nla/yaz4j

více o instalaci (a buildu .so souboru) yaz4j
http://www.indexdata.com/blog/2010/02/building-simple-http-z3950-gateway-using-yaz4j-and-tomcat

sample projekt, ve kterém si zatím zkouším implementaci
https://github.com/jirikrepl/maven-archetype-quickstart-yaz4j

**Comment by black23** [comment]
Super! Až bude možné testovat, dejte vědět. Zkusíme an pár Zkach, které běžně používáme.

**Comment by MartinRumanek** [comment]
@jirikrepl Oficiální repo je zde https://github.com/indexdata/yaz4j a z něho se mi to v pohodě zbuildí (samozřejmě mám nainstalované balíčky swig a libyaz-devel).

To s tou minor verzí to po tobě chce právě novější javu a ne tu starou. A jakou javu si maven vybere ovlivňuješ proměnnou prostředí JAVA_HOME.

**Comment by jirikrepl** [comment]
#67

**Comment by MartinRumanek** [comment]
Bohužel nefunguje.

**Comment by black23** [comment]
Budeš na tom pracovat? Nám by se to hodilo pro přebírání lokálních záznamů místo přebírání odjinud, které často nevyhovují.

**Comment by MartinRumanek** [comment]
@black23 Byla to nakonec jenom drobnost :-)
