### ISSUE TITLE
Nedokončený proces mazání objektu spuštěný z Meditu způsobí, že tento pak není možné odstranit z Fedory

### ISSUE THREAD

**Issue by black23** [moravianlibrary/MEditor#63]
Log K5
`om.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy32.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	... 13 more

Mar 24, 2016 1:45:32 PM cz.incad.kramerius.indexer.Indexer update
SEVERE: Update failed
java.lang.Exception: java.lang.Exception: Fedora Object uuid:9fb8ed2b-daca-4527-809c-3816930b900a not found. 
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:168)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: java.lang.Exception: Fedora Object uuid:9fb8ed2b-daca-4527-809c-3816930b900a not found. 
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:72)
	at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:352)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:111)
	... 11 more
Caused by: javax.xml.ws.soap.SOAPFaultException:  Caused by: no path in db registry for [uuid:9fb8ed2b-daca-4527-809c-3816930b900a]
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy32.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	... 13 more

Mar 24, 2016 1:45:32 PM cz.incad.kramerius.indexer.Indexer run
SEVERE: Run failed
java.lang.Exception: Index process failed
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:86)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)

Mar 24, 2016 1:45:32 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: java.lang.Exception: java.lang.Exception: Index process failed
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:95)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	... 5 more
Caused by: java.lang.Exception: Index process failed
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:86)
	... 6 more

`

**Comment by MartinRumanek** [comment]
@jirikrepl + By bylo fajn, kdyby Editor uměl smazat i takto haluzově rozbité dokumenty https://github.com/moravianlibrary/kramerius/issues/78
