### ISSUE TITLE
Chybová hláška

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#83]
Při ukládání/aktualizaci objektu editor vyhazuje hlášku:
Connection cannot be established. Please check whether Fedora is running.
Jeden proces spadl asi kvůli tomuto:
javax.xml.ws.soap.SOAPFaultException:  Caused by: no path in db registry for [uuid:uuid:ab399a86-0c3b-4a7c-9a15-db75ad0f1499]

**Comment by LenkaDamborska** [comment]
Zopakováno dnes 13:58 :) PID 27279

**Comment by jdobiasovsky** [comment]
Máme stejný problém.
Aktualizace / uložení obrázku do Fedory selže, ale metadata se nahrají. 

V logu je tato chyba:
```
10:28:16 ERROR (FedoraUtils.java:912) - Digital object uuid%253A4ba9bc6b-b814-4c51-8231-e7a7257ffb6c is not in the repository. Cannot get RELS EXT stream.       
10:28:16 ERROR (GetDigitalObjectDetailHandler.java:215) - Connection cannot be established. Please check whether Fedora is running.
```

**Comment by jirikrepl** [comment]
Toto bude problém s indexací v Krameriu. Zde je celý chybový výpis procesu s PID *27279*

	Aug 03, 2016 1:58:51 PM cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
	SEVERE: Error getting object
	javax.xml.ws.soap.SOAPFaultException:  Caused by: no path in db registry for [uuid:uuid:40ed417a-57e6-11e0-87d9-0050569d679d]
		at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
		at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
		at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
		at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
		at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
		at com.sun.proxy.$Proxy34.export(Unknown Source)
		at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
		at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:352)
		at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:111)
		at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
		at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
		at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
		at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
		at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
		at cz.incad.kramerius.indexer.Main.main(Main.java:47)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)

	Aug 03, 2016 1:58:51 PM cz.incad.kramerius.indexer.SolrOperations updateIndex
	SEVERE: Cant index. Action:fromKrameriusModel Value: uuid:uuid:40ed417a-57e6-11e0-87d9-0050569d679d
	java.lang.Exception: Fedora Object uuid:uuid:40ed417a-57e6-11e0-87d9-0050569d679d not found. 
		at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:72)
		at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:352)
		at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:111)
		at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
		at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
		at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
		at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
		at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
		at cz.incad.kramerius.indexer.Main.main(Main.java:47)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
	Caused by: javax.xml.ws.soap.SOAPFaultException:  Caused by: no path in db registry for [uuid:uuid:40ed417a-57e6-11e0-87d9-0050569d679d]
		at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
		at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
		at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
		at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
		at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
		at com.sun.proxy.$Proxy34.export(Unknown Source)
		at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
		... 13 more

	Aug 03, 2016 1:58:51 PM cz.incad.kramerius.indexer.Indexer update
	SEVERE: Update failed
	java.lang.Exception: java.lang.Exception: Fedora Object uuid:uuid:40ed417a-57e6-11e0-87d9-0050569d679d not found. 
		at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:168)
		at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
		at cz.incad.kr

**Comment by jirikrepl** [comment]
Výše popsaný problém se projevuje při otevření dokumentu v Editoru přes Krameria (kliknutí na položku *editor částí* v menu). Následně se dokument v Editoru upraví a publikuje. Potom selhává indexace v Krameriu.

Problém se nám podařilo problém replikovat s dokumentem `uuid:40867e28-2d1d-4fdd-ac74-e914578db33b`. I ostatní dokumenty se takto chovaly. Které pole jsme měnily v MODS a DC @LenkaDamborska ?

Dnes to vypadá, že vše funguje. Indexace proběhne v pořádku.

**Comment by LenkaDamborska** [comment]
@jirikrepl Hrala jsem si s dc.creator a mods:name. DC.creator se promita do SOLR.

**Comment by LenkaDamborska** [comment]
Jak jsem pochopila jde o problém s Firefoxem - https://github.com/moravianlibrary/MEditor/issues/93. Toto issue zavírám.
