### ISSUE TITLE
Nelze nahrát PDF dokumenty do Fedory

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/MEditor#94]
Zatím nevíme, jestli je to problém editoru nebo Fedory nebo něčeho jiného, ale do Fedory není možné dostat PDF dokumenty. Editor je zobrazí i zpracuje bez problémů, ale ve Fedoře pak nejsou. Vytvoří se pouze digitální objekt bez pdf souboru. V červnu to ještě bylo ok.

**Comment by LenkaDamborska** [comment]
Ve FOXML těch nových PDF chybí datastreamy IMG_FULL, IMG_THUMB, IMG_PREVIEW, POLICY. Zkoušela jsem zpracovat monografii s jp2 obrázky a tam nebyl problém. Jediný rozdíl je v tom, že obrázky se přetahují do struktury k monografii, zatímco u PDF dokumentů se PDF nepřetahuje. 
Editor s tímto neměl žádný problém ani Fedora, ale ve FOXML to pdf vůbec není.

**Comment by MartinRumanek** [comment]
Stalo se to znovu:

http://kramerius.mzk.cz/search/i.jsp?pid=uuid:9783c828-e5f4-4ef4-8174-c1042eabddba

**Comment by MartinRumanek** [comment]
Je to chyba naší Fedory, jinde se to nechce projevit

```
meditor_1         | java.io.IOException: Server returned HTTP response code: 413 for URL: http://fedora.dk-back.infra.mzk.cz/fedora/objects/uuid:11d49d4c-4f4c-4730-a1db-60da2dea6c2f/datastreams/IMG_FULL?controlGroup=M&versionable=true&dsState=A&mimeType=application/pdf
meditor_1         | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
meditor_1         | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
meditor_1         | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
meditor_1         | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
meditor_1         | 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
meditor_1         | 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
meditor_1         | 	at java.security.AccessController.doPrivileged(Native Method)
meditor_1         | 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
meditor_1         | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
meditor_1         | 	at cz.mzk.editor.server.util.RESTHelper.openConnection(RESTHelper.java:221)
meditor_1         | 	at cz.mzk.editor.server.util.RESTHelper.putOrPost(RESTHelper.java:255)
meditor_1         | 	at cz.mzk.editor.server.util.RESTHelper.post(RESTHelper.java:326)
meditor_1         | 	at cz.mzk.editor.server.newObject.CreateObject.insertManagedDatastream(CreateObject.java:709)
meditor_1         | 	at cz.mzk.editor.server.newObject.CreateObject.handlePdf(CreateObject.java:568)
meditor_1         | 	at cz.mzk.editor.server.newObject.CreateObject.insertFOXML(CreateObject.java:537)
meditor_1         | 	at cz.mzk.editor.server.newObject.CreateObject.insertFOXML(CreateObject.java:223)
meditor_1         | 	at cz.mzk.editor.server.newObject.CreateObject.insertAllTheStructureToFOXMLs(CreateObject.java:208)
meditor_1         | 	at cz.mzk.editor.server.handler.InsertNewDigitalObjectHandler.execute(InsertNewDigitalObjectHandler.java:145)
meditor_1         | 	at cz.mzk.editor.server.handler.InsertNewDigitalObjectHandler.execute(InsertNewDigitalObjectHandler.java:67)
meditor_1         | 	at com.gwtplatform.dispatch.rpc.server.AbstractDispatchImpl.doExecute(AbstractDispatchImpl.java:154)
meditor_1         | 	at com.gwtplatform.dispatch.rpc.server.AbstractDispatchImpl.execute(AbstractDispatchImpl.java:110)
meditor_1         | 	at com.gwtplatform.dispatch.rpc.server.AbstractDispatchServiceImpl.execute(AbstractDispatchServiceImpl.java:87)
meditor_1         | 	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
meditor_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
meditor_1         | 	at java.lang.reflect.Method.invoke(Method.java:606)
meditor_1         | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
meditor_1         | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
meditor_1         | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
meditor_1         | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
meditor_1         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
meditor_1         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
meditor_1         | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
meditor_1         | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
meditor_1         | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
meditor_1         | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
meditor_1         | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
meditor_1         | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
meditor_1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
meditor_1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
meditor_1         | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
meditor_1         | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
meditor_1         | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
meditor_1         | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
meditor_1         | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
meditor_1         | 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:581)
meditor_1         | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
meditor_1         | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
meditor_1         | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
meditor_1         | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
meditor_1         | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
meditor_1         | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
meditor_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
meditor_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
meditor_1         | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
meditor_1         | 	at java.lang.Thread.run(Thread.java:745)
meditor_1         | Caused by: java.io.IOException: Server returned HTTP response code: 413 for URL: http://fedora.dk-back.infra.mzk.cz/fedora/objects/uuid:11d49d4c-4f4c-4730-a1db-60da2dea6c2f/datastreams/IMG_FULL?controlGroup=M&versionable=true&dsState=A&mimeType=application/pdf
meditor_1         | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
meditor_1         | 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
meditor_1         | 	at cz.mzk.editor.server.util.RESTHelper.openConnection(RESTHelper.java:216)
meditor_1         | 	... 45 more
meditor_1         | 08:00:44 ERROR (CreateObject.java:733) - An error occured during inserting an IMG_FULL file: /root/output/editor.mzk.cz/74a09b43-eb7d-3210-adda-5255b2927864.pdf to the digital object: uuid:11d49d4c-4f4c-4730-a1db-60da2dea6c2f as a IMG_FULL datastream.
meditor_1         | cz.mzk.editor.client.ConnectionException: connection to http://fedora.dk-back.infra.mzk.cz/fedora/objects/uuid:11d49d4c-4f4c-4730-a1db-60da2dea6c2f/datastreams/IMG_FULL?controlGroup=M&versionable=true&dsState=A&mimeType=application/pdf cannot be established
```
